name: ci

on:
  push:
    branches:
      - 'build'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run script to change files and ensure docker build is good
        run: |
          build/workflow.sh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
  
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/sophre-testing:latest
          build-args: |
            ADMIN_PASSWORD=${{secrets.ADMIN_PASSWORD}}

