name: ci

on:
  push:
    branches:
      - 'deploy'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # This is used so that the ant command can be used from insdie the workflow.sh file 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      -
        name: Run script to change files and ensure docker build is good
        run: |
          "${GITHUB_WORKSPACE}/build/workflow.sh"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/sophre-testing:latest
          build-args: |
            ADMIN_PASSWORD=${{secrets.ADMIN_PASSWORD}}
